import { execSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { defineConfig, loadEnv } from "vite";

const GENERATED_PATH = fileURLToPath(
  new URL("./src/version-generated.ts", import.meta.url),
);

function tryGit(args: string): string | null {
  try {
    return execSync(`git ${args}`, { stdio: ["ignore", "pipe", "ignore"] })
      .toString()
      .trim();
  } catch {
    return null;
  }
}

function readNominalVersion(): string {
  try {
    const pkgPath = fileURLToPath(new URL("./package.json", import.meta.url));
    const pkg = JSON.parse(readFileSync(pkgPath, "utf-8")) as { version?: string };
    if (pkg.version) return pkg.version;
  } catch {
    // fall through
  }
  return "0.0.0";
}

function isDirty(): boolean {
  const out = tryGit("status --porcelain");
  if (!out) return false;
  // Exclude the generated file itself — vite rewrites it at startup, so it
  // would otherwise produce a self-perpetuating "-dirty" loop on every boot.
  const meaningful = out
    .split("\n")
    .map((l) => l.trim())
    .filter((l) => l && !l.endsWith("src/version-generated.ts"));
  return meaningful.length > 0;
}

function computeFrontendVersion(): {
  display: string;
  longSha: string;
  commitDate: string | null;
} {
  const nominal = readNominalVersion();
  const shortSha = tryGit("rev-parse --short HEAD");
  const longSha = tryGit("rev-parse HEAD");
  const commitDate = tryGit("log -1 --format=%cI");

  if (!shortSha || !longSha) {
    return { display: `${nominal}+unknown`, longSha: "unknown", commitDate: null };
  }
  const dirty = isDirty() ? "-dirty" : "";
  return {
    display: `${nominal}+${shortSha}${dirty}`,
    longSha,
    commitDate,
  };
}

function writeGeneratedVersion(): void {
  const fe = computeFrontendVersion();
  const generated =
    `// Generated by vite at startup. Disk content is overwritten on each\n` +
    `// vite boot so vitest (which does not run vite) sees the most recent\n` +
    `// values. The file exists in git for vitest's import resolution.\n` +
    `export const FRONTEND_DISPLAY = ${JSON.stringify(fe.display)};\n` +
    `export const FRONTEND_LONG_SHA = ${JSON.stringify(fe.longSha)};\n` +
    `export const FRONTEND_COMMIT_DATE: string | null = ${JSON.stringify(fe.commitDate)};\n`;
  let existing = "";
  try {
    existing = readFileSync(GENERATED_PATH, "utf-8");
  } catch {
    // first write
  }
  if (existing !== generated) {
    writeFileSync(GENERATED_PATH, generated);
  }
}

writeGeneratedVersion();

export default defineConfig(({ mode }) => {
  const env = loadEnv(mode, process.cwd(), "");
  const target = env.VITE_PROXY_TARGET || "http://127.0.0.1:8000";

  const onProxyError = (err: Error) => {
    console.warn(`[vite] proxy error (non-fatal): ${err.message}`);
  };

  const apiProxy = {
    "/build": { target, changeOrigin: true },
    "/tasks": { target, changeOrigin: true },
    "/monitor": { target, changeOrigin: true },
    "/health": { target, changeOrigin: true },
    "/version": { target, changeOrigin: true },
    "/workers": { target, changeOrigin: true },
    "/config": { target, changeOrigin: true },
    "/schedules": { target, changeOrigin: true },
    "/grill": { target, changeOrigin: true },
    "/mgrill": { target, changeOrigin: true },
    "/arcade": { target, changeOrigin: true },
    "/repos": { target, changeOrigin: true },
  } as Record<string, object>;

  for (const key of Object.keys(apiProxy)) {
    (apiProxy[key] as Record<string, unknown>).configure = (
      proxy: { on: (event: string, handler: (...args: unknown[]) => void) => void },
    ) => {
      proxy.on("error", onProxyError);
    };
  }

  // Skip WS proxy in CI — no backend is running; e2e tests mock all routes.
  if (!process.env.CI) {
    apiProxy["/ws"] = {
      target,
      changeOrigin: true,
      ws: true,
      configure: (proxy: { on: (event: string, handler: (...args: unknown[]) => void) => void }) => {
        proxy.on("error", onProxyError);
      },
    };
  }

  return { server: { proxy: apiProxy } };
});
