#!/usr/bin/env node
/**
 * Writes frontend/src/version-generated.ts with the current git SHA, dirty
 * flag, and nominal version from package.json. Invoked before vite starts
 * (via run-local-stack.sh and as a predev hook). Doing this in a Node
 * script — rather than vite.config.ts — bypasses opaque vite config-load
 * issues observed on lugia where top-level side effects in vite.config.ts
 * did not execute reliably.
 */
import { execSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const FRONTEND_ROOT = fileURLToPath(new URL("..", import.meta.url));
const PKG_PATH = fileURLToPath(new URL("../package.json", import.meta.url));
const TARGET_PATH = fileURLToPath(
  new URL("../src/version-generated.ts", import.meta.url),
);

function tryGit(args) {
  try {
    return execSync(`git ${args}`, {
      cwd: FRONTEND_ROOT,
      stdio: ["ignore", "pipe", "ignore"],
    })
      .toString()
      .trim();
  } catch {
    return null;
  }
}

function readNominalVersion() {
  try {
    const pkg = JSON.parse(readFileSync(PKG_PATH, "utf-8"));
    if (pkg.version) return pkg.version;
  } catch {
    // fall through
  }
  return "0.0.0";
}

function isDirty() {
  const out = tryGit("status --porcelain");
  if (!out) return false;
  const meaningful = out
    .split("\n")
    .map((l) => l.trim())
    .filter((l) => l && !l.endsWith("src/version-generated.ts"));
  return meaningful.length > 0;
}

function main() {
  const nominal = readNominalVersion();
  const shortSha = tryGit("rev-parse --short HEAD");
  const longSha = tryGit("rev-parse HEAD");
  const commitDate = tryGit("log -1 --format=%cI");

  let display, longShaOut, commitDateOut;
  if (!shortSha || !longSha) {
    display = `${nominal}+unknown`;
    longShaOut = "unknown";
    commitDateOut = null;
  } else {
    const dirty = isDirty() ? "-dirty" : "";
    display = `${nominal}+${shortSha}${dirty}`;
    longShaOut = longSha;
    commitDateOut = commitDate || null;
  }

  const generated =
    `// Generated by frontend/scripts/write-version.mjs before vite starts.\n` +
    `// Disk content is overwritten on each run; the placeholder committed\n` +
    `// in git is what vitest uses (vitest does not invoke this script).\n` +
    `export const FRONTEND_DISPLAY = ${JSON.stringify(display)};\n` +
    `export const FRONTEND_LONG_SHA = ${JSON.stringify(longShaOut)};\n` +
    `export const FRONTEND_COMMIT_DATE: string | null = ${JSON.stringify(commitDateOut)};\n`;

  let existing = "";
  try {
    existing = readFileSync(TARGET_PATH, "utf-8");
  } catch {
    // file doesn't exist yet
  }
  if (existing !== generated) {
    writeFileSync(TARGET_PATH, generated);
    console.log(`[write-version] wrote ${display} -> src/version-generated.ts`);
  } else {
    console.log(`[write-version] up to date: ${display}`);
  }
}

main();
