// Generated by frontend/scripts/write-version.mjs before vite starts.
// Disk content is overwritten on each run; the placeholder committed
// in git is what vitest uses (vitest does not invoke this script).
export const FRONTEND_DISPLAY = "0.1.0+4d6ffdd-dirty";
export const FRONTEND_LONG_SHA = "4d6ffddd1523b0092791560e16d1117c283a616c";
export const FRONTEND_COMMIT_DATE: string | null = "2026-05-04T19:20:51+01:00";
