// Generated by frontend/scripts/write-version.mjs before vite starts.
// Disk content is overwritten on each run; the placeholder committed
// in git is what vitest uses (vitest does not invoke this script).
export const FRONTEND_DISPLAY = "0.0.0+dev";
export const FRONTEND_LONG_SHA = "dev";
export const FRONTEND_COMMIT_DATE: string | null = null;
