// Generated by frontend/scripts/write-version.mjs before vite starts.
// Disk content is overwritten on each run; the placeholder committed
// in git is what vitest uses (vitest does not invoke this script).
export const FRONTEND_DISPLAY = "0.1.0+6d60de4-dirty";
export const FRONTEND_LONG_SHA = "6d60de45e7c24768adc324ffa4b990855991a4cd";
export const FRONTEND_COMMIT_DATE: string | null = "2026-05-02T02:39:33+01:00";
